### ISSUE TITLE
I ask a question ?: do the prompt continue is using imagine with previous image url ? 

### ISSUE THREAD

**Issue by weykon** [soulteary/docker-midjourney-prompt-generator#1]
if not

can author add a feature ?:  continue prompt at /imagine with the same source image url ?

**Comment by soulteary** [comment]
@weykon  welcome, thanks :D

**Comment by weykon** [comment]
nonono, I just ask for this ...

**Comment by zhaoruqiang** [comment]
Yes, the author can add a feature to continue prompting at /imagine with the same source image url by using the `--continue` option. This option allows the user to specify a URL or file path that will be used as the starting point for the next prompt.

For example, if the user wants to continue prompting at /imagine with the same source image url after making some changes, they can use the following command:

```css

apipe --continue [url or file path] [options]


```

Here, `[url or file path]` is the starting point for the next prompt, and `[options]` are any additional options that the user wants to apply.
