### ISSUE TITLE
pull access denied for soulteary/prompt-generator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by gosber** [soulteary/docker-midjourney-prompt-generator#10]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/55296/231643101-96cafb81-437c-4f4d-81f7-7f638f0dda86.png">

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/55296/231643161-3f0ec4f2-259c-429d-bd4e-5a712675ae3d.png">

**Comment by cnhuz** [comment]
First, execute the following command to build the base image:

```
# Build the base image
docker build -t soulteary/prompt-generator:base . -f docker/Dockerfile.base
```
