### ISSUE TITLE
部署报错：failed to solve: rpc error: code = Unknown desc

### ISSUE THREAD

**Issue by zarswow** [soulteary/docker-midjourney-prompt-generator#5]
![image](https://user-images.githubusercontent.com/103822120/230941784-219b9718-6c53-4eb2-9007-82fcdac2ccbd.png)

纯小白瞎凑合学习 Prompts 果不其然卡住了哈哈哈，问了 GPT 没问出个所以然，求求大佬解惑以下 🫡

**Comment by soulteary** [comment]
这里看了下，应该是 docker 版本的问题，升级 docker 版本应该可解。 @zarswow
